{
  "formatVersion": "0.4",
  "component": {
    "group": "org.example",
    "module": "leaf-bar",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.8",
      "buildId": "tl5wwkf5knektm7d7hd2bvjvki"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.example",
          "module": "base-foo",
          "version": {
            "prefers": "1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.example",
          "module": "leaf-baz",
          "version": {
            "prefers": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "leaf-bar-1.1.jar",
          "url": "leaf-bar-1.1.jar",
          "size": 686,
          "sha1": "f868053d178dddf93f58e47030174f30ff7d6529",
          "md5": "65c1856cccfcb6bffa2c1ede2cea3c61"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.example",
          "module": "base-foo",
          "version": {
            "prefers": "1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.example",
          "module": "leaf-baz",
          "version": {
            "prefers": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "leaf-bar-1.1.jar",
          "url": "leaf-bar-1.1.jar",
          "size": 686,
          "sha1": "f868053d178dddf93f58e47030174f30ff7d6529",
          "md5": "65c1856cccfcb6bffa2c1ede2cea3c61"
        }
      ]
    }
  ]
}
