{
  "formatVersion": "0.4",
  "component": {
    "group": "org.example",
    "module": "leaf-bar",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.8",
      "buildId": "f7rhmo7ccbaxxh3hhrpyph5tzy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.example",
          "module": "base-foo",
          "version": {
            "prefers": "2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.example",
          "module": "leaf-baz",
          "version": {
            "prefers": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "leaf-bar-2.0.jar",
          "url": "leaf-bar-2.0.jar",
          "size": 686,
          "sha1": "f4d454caa82328692e55fde3211aa2641fb8650f",
          "md5": "d48c1504cb78f864d3f4d79a11cdee06"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.example",
          "module": "base-foo",
          "version": {
            "prefers": "2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.example",
          "module": "leaf-baz",
          "version": {
            "prefers": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "leaf-bar-2.0.jar",
          "url": "leaf-bar-2.0.jar",
          "size": 686,
          "sha1": "f4d454caa82328692e55fde3211aa2641fb8650f",
          "md5": "d48c1504cb78f864d3f4d79a11cdee06"
        }
      ]
    }
  ]
}
